apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xrd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AnasSahel/gitops-crossplane-argocd
    path: argocd/xrd
    targetRevision: HEAD
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2 
        maxDuration: 1m
  