apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crossplane-azure-default-external-secret
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-crossplane
    kind: SecretStore
  target:
    name: crossplane-azure-default-secret
    creationPolicy: Owner
  data:
    - secretKey: azure-creds
      remoteRef:
        key: azure-credentials
