apiVersion: v1
data:
  appId: NDY1YzNjMTgtZmE5MC00NDExLWI0YTEtZDgzODc0ZTEwYjk4
  clientId: NDY1YzNjMTgtZmE5MC00NDExLWI0YTEtZDgzODc0ZTEwYjk4
  clientSecret: a3BXOFF+c1IyQXJtV1VId3I1Wk16MW5ZSGpPN0VKenRxZ1A0aGNoaQ==
  password: a3BXOFF+c1IyQXJtV1VId3I1Wk16MW5ZSGpPN0VKenRxZ1A0aGNoaQ==
  tenantId: IjAwNjU1N2Y1LTAyMjEtNDZlNy04OTA5LWQ1ZDBmODg5YTI3MCI=
kind: Secret
metadata:
  creationTimestamp: "2025-02-18T11:44:20Z"
  name: sp-crossplane-secret
  namespace: argocd
  resourceVersion: "21737"
  uid: df63f29e-ed21-497d-8614-5e08b7077ddc
type: Opaque
