apiVersion: compute.trustin.tech/v1alpha1
kind: VirtualMachineClaim
metadata:
  name: my-namespaced-vm
  namespace: crossplane-test
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: ArgoCD
spec:
  location: "EU"
