apiVersion: v1
kind: Secret
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: external-secrets
  url: https://charts.external-secrets.io
  type: helm
