apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-rg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AnasSahel/gitops-crossplane-argocd
    path: infrastructure/azure-rg
    targetRevision: HEAD
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m