apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: eso-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background

spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.14.2
    chart: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
