apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-helm-external-secrets
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: external-secrets/external-secrets
  type: helm
  url: https://charts.external-secrets.io
