apiVersion: external-secrets.io/v1beta1
kind: SecretStore

metadata:
  name: secretstore-crossplane

spec:
  provider:
    azurekv:
      tenantId: "006557f5-0221-46e7-8909-d5d0f889a270"
      vaultUrl: "https://kv-gitops-sbx-01.vault.azure.net/"
      authSecretRef:
        clientId:
          name: "sp-eso-sbx-01"
          key: "clientId"
        clientSecret:
          name: "sp-eso-sbx-01"
          key: "clientSecret"
