apiVersion: external-secrets.io/v1beta1
kind: SecretStore

metadata:
  name: secretstore-crossplane
  namespace: crossplane-system
  # annotations:
  #   argocd.argoproj.io/sync-wave: "1"

spec:
  provider:
    azurekv:
      tenantId: "006557f5-0221-46e7-8909-d5d0f889a270"
      vaultUrl: "https://kv-gitops-sbx-01.vault.azure.net"
      authSecretRef:
        clientId:
          name: sp-crossplane-secret
          key: clientId
        clientSecret:
          name: sp-crossplane-secret
          key: clientSecret
