apiVersion: v1
kind: Secret
metadata:
  name: crossplane
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: crossplane-stable
  url: https://charts.crossplane.io/stable
  type: helm
