apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-namespace.yaml
  - argocd-cm-patch.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/notifications_catalog/install.yaml
# patches:
#   - target:
#       version: v1
#       kind: ConfigMap
#       name: argocd-cm
#     path: argocd-cm-patch.yaml
