apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Make sure argocd is in the argocd namespace...
# it seems a workaround, otherwise, it's in the defaul
namespace: argocd

resources:
  - argocd-namespace.yaml
  # - https://raw.githubusercontent.com/argoproj/argo-cd/refs/heads/master/manifests/ha/install.yaml
  - argocd-repo-crossplane.yaml
  - argocd-repo-external-secrets.yaml

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
    path: patch-argocd-cm.yaml
