apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-namespace.yaml
  - argocd-cm-patch.yaml
# patches:
#   - target:
#       version: v1
#       kind: ConfigMap
#       name: argocd-cm
#     path: argocd-cm-patch.yaml
