apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: crossplane-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/AnasSahel/gitops-crossplane-argocd.git
    targetRevision: HEAD
    path: platforms/crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
