apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: crossplane-system
  namespace: argocd
  labels:
    gitops.trustin.tech/gitops: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.18.2
    chart: crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
