apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: crossplane-system
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground

spec:
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.19.0
    chart: crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
