apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-helm-crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: crossplane-stable
  url: https://charts.crossplane.io/stable
  type: helm
