apiVersion: azure.upbound.io/v1beta1
metadata:
  name: azure-default
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: crossplane-azure-default-secret
      key: azure-creds
