apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: example-resources-random
spec:
  forProvider:
    location: West Europe
    tags:
      provisioner: crossplane
  providerConfigRef:
    name: azure-default
