apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-gitops
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/AnasSahel/gitops-crossplane-argocd.git
        revision: HEAD
        directories:
          - path: argo-gitops/*
  template:
    metadata:
      name: "app-{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/AnasSahel/gitops-crossplane-argocd.git
        targetRevision: HEAD
        path: argo-gitops/crossplane
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
