apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Make sure argocd is in the argocd namespace...
# it seems a workaround, otherwise, it's in the defaul
namespace: argocd

resources:
  - ../../base
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

secretGenerator:
  - name: private-repo-main
    namespace: argocd
    envs:
      - private-repo-main.env
    literals:
      - name=gitops-repo-main
      - type=git
    options:
      labels:
        argocd.argoproj.io/secret-type: repo-creds
