apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

secretGenerator:
  - name: private-repo-main
    namespace: argocd
    envs:
      - private-repo-main.env
    literals:
      - name=gitops-repo-main
      - type=git
    options:
      labels:
        argocd.argoproj.io/secret-type: repo-creds
